---
title: "About Data Science"
format: html
editor: visual
---

## Some Information about Statisticians and Data Scientists

What do I think being a data scientist is about?

From reading the multiple sources, I think it is hard to pin down exactly what a data scientist is, since it seems it is up to interpretation and expert opinion. If I had to break it down very simply, a data scientist is an expert in data from cleaning it up to use all the way to applying it in a very specific setting. A lot of the articles try to make a distinction between a statistician and a data scientist, and to me, it seems like a data scientist has broader skills and increased activities they may be responsible for when comparing to a statistician.

Overall, below are some of skills I think a data scientist would perform. I don’t believe 1 person would always necessary perform all of these, but it seems for someone to excel in this field, they need a general understanding of all these tasks, even if they specialize in only a part of the process.

A data scientist could:

-   Take raw data from multiple sources and “clean” it to create 1 large data set

-   Manipulate the “cleaned” data to make it easier to use and make initial summaries of the data

-   Create models to apply to the data to answer a question. These models are more likely to take real time data to provide results (as compared to retrospective data of say a clinical trial and just apply statistical tests to) and help someone to adjust plans to improve outcomes

-   Be responsible for leading a team by communicating limitations of data, keeping teams on track, ensuring the problem could be answered by the data, and knowing when to accept failure

-   Ensure a team is trying to solve the right problem and knowing where to dedicate resources

-   Needs not only knowledge in data manipulation and coding, but a general understanding of the field they are providing the model or output for

What are some differences between statisticians and data scientists?

Some of the differences between statisticians and data scientists are noted above, but in a bit more detail, I think statisticians have a focus that is a bit narrower than compared to data scientists.

Statisticians are involved in not only in the creation of experiments or surveys designed to answer a hypothesis, but also may be part of the data collection process. A statistician is more likely to work with cleaned, structured data, which is likely smaller in size than compared to what a data scientist would work with. Statisticians seem to have a greater background in math, with additional knowledge/expertise in computer programming. The background in math, leads a statistician to mainly work using statistical tests and models to fit retrospective data to answer the hypothesis. The statistician is probably more likely to provide an answer to a question that indicates whether a particular outcome is due to the intervention or random chance. Finally, a statistician is not required to have knowledge of a particular area in which the experiment is performed, as they may only need to provide the results of the tests and not an analysis. For example, a statistician may provide the results of a statistical test for a pharmaceutical trial, but they do not necessarily need to know how the results would affect patient care.

Meanwhile, data scientists would be more involved in using data gathered from multiple sources and be required to clean them to combine the data into a usable format. The data scientist is going to then use the data to create a model to solve a business-like decision. The data used for this decision, is more likely prospective or real-time than the data a statistician would use. Data scientists have a broader range of education disciplines when compared to a statistician, such as data scientists could have a background in engineering as opposed to mathematics. The data scientist would also need to know enough about the field the data is being used in, to help guide teams to ensure the questions can be answered and that the data being used is appropriate to be used in the model. As a result, the data scientist can either lead a team or be a significant member of a team. Whereas, a statistician could function in a silo and still be effective. Finally, data scientists focus more on a practical technique versus a statistician’s work may be more theoretical.

How do I view myself in relation to statisticians and data scientists?

In relation to these, I want to be able to be knowledgeable to perform some of the activities both a statistician and data scientist. I took this graduate certificate program to gain additional knowledge to perform my job in a different way and elevate some of the services I can provide. I am a pharmacy coordinator at a community health system within North Carolina.

In relation to a statistician, I oversee and coordinate pharmacy resident research projects during their training. Almost all these studies are retrospective in nature with an aim towards quality improvement, lasting for around 1 year. I would like to be able to identify the statistical tests we should run for the outcomes and be able to perform those tests. The data sets used for these projects will likely have \< 250 or so patients and would be in a format that is easy to manipulate and perform the tests. To me, this is what a statistician would do and I aim to be able to have some knowledge to do this. Our projects are normally basic, so most outcomes can be done using a chi-square or t-test. However, since my primary field is pharmacy, I may have more knowledge in how to apply these results than someone may be required to who is primarily a statistician.

Regarding data scientists, I also work a lot with our Pharmacy and Therapeutic’s committees to make formulary decisions regarding new and existing medication therapy. With this, I am using both retrospective and real time data to help make decisions to optimize our use of drugs and ensure we are being good stewards in relation to financial expenditures. While I do not have the ability to access the raw data, the information I need to make these decisions comes from many different sources. Some of the data that I can obtain from databases within our medical record can easily be manipulated and I can get down to patient level information. In other instances, I need to use programs and databases provided by vendors, which don’t have patient level data, and many have minimal ways in which to manipulate the data I am seeing. I must use my pharmacy knowledge to connect these different programs together to make an informed decision. The data used to make these decisions is more real-time than our research projects. We are using the models provided from the vendors to help make decisions or identify areas we can improve, but we need to do additional work to see if they truly will have an impact.

## Some R Code

```{r}
#| echo: false #hide code
y <- density(iris$Petal.Width) #define y
class(y) #determine class of y
typeof(y) #determine type of y
str(y) #determine structure of y
plot(y) #plot y
```
